server:
  port: 0

spring:
  application:
    name: RENTAL-SERVICES

  datasource:
    url: jdbc:h2:mem:rentaldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    import: optional:configserver:http://localhost:8888
